"""empty message

Revision ID: a22b1ac53a4e
Revises: 009a952c9696
Create Date: 2020-05-01 21:13:39.948549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22b1ac53a4e'
down_revision = '009a952c9696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('Movie', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Movie', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
